### PR TITLE
Upgrade React v17 to v18

### PR DESCRIPTION
**Pull request by bluin4308**
Hello. I suggest you update React to v18. Tested in **Firefox 111.0 64bit** and **Google Chrome 111.0.5563.65 64bit**. No bugs were found.

### CODE REVIEW

**Comment by joshhunt** [comment]
Why?

**Comment by bluin4308** [comment]
Why not?

**Comment by bluin4308** [comment]
That's not a very correct answer, sorry. I was going to refactor your extension in the forked repo and I thought it would be nice to open a PR to your repo.

**Comment by joshhunt** [comment]
No, there must be a reason why to make a change. Changes for change sake are not useful.

The extension works and it's unlikely I will release an update to this extension, so this would make the code non-representative of what's published in AMO.

**Pull request closed without merging**
